---
application:
  name: "backend-tehiri-local"
  project: "tehiri-strappi"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "strapi"
  version: "12"
routers:
- name: "main-backend-tehiri-local"
  routes:
  - application_name: "backend-tehiri-local"
    paths:
    - "/*"
